version: '3.7'
services:
  user-service:
    build:
      context: ""
    restart: always
    container_name: user-service
    command: sh ./user_service.sh
    ports:
      - 8081:8080
    networks:
      - eventbus-network
    environment:
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_DB_NAME: ${PG_DB_NAME}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
networks:
  eventbus-network:
    external: true
