version: '3.7'
services:
  user-service:
    build:
      context: ""
    restart: always
    container_name: user-service
    command: sh ./user_service.sh
    ports:
      - 8081:8080
    networks:
      - eventbus-network
networks:
  eventbus-network:
    external: true
