#!/bin/bash
set -e

POSTGRES="psql --username ${POSTGRES_USER}"

echo "Creating databases: ${EVENTBUS_DB_USERSERVICE} and ${EVENTBUS_DB_ML_MODEL}"

$POSTGRES <<EOSQL
CREATE USER ${POSTGRES_USER};
ALTER USER ${POSTGRES_USER} WITH SUPERUSER;

CREATE DATABASE ${EVENTBUS_DB_USERSERVICE} OWNER ${POSTGRES_USER};
CREATE DATABASE ${EVENTBUS_DB_ML_MODEL} OWNER ${POSTGRES_USER};
EOSQL
