version: '3.7'
services:
  user-service:
    build:
      context: ""
    restart: always
    container_name: model-service
    command: sh ./model_service.sh
    ports:
      - 8082:8080
    networks:
      - eventbus-network
networks:
  eventbus-network:
    external: true
